/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visão;

import Conexão.Conexao;
import Dao.LoginSessao_Dao;
import Dao.TestarConexao_Dao;
import Dao.Usuario_Dao;
import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.net.InetAddress;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.UnknownHostException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.TimeZone;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Suporte T.I 2
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    String data, conexao, teste,ipDaMaquina;
    int Cod_usuario,Cod_Perfil_Permitido;
    public MenuPrincipal() {
        initComponents();
        //setExtendedState(MAXIMIZED_BOTH);//Abrir tela maximizada
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Imagens/lOGO HR INR_2.png")).getImage());//Icone
        MostrarHOra();
        MostrarData();
        PegarIp();
        
    }
    
      //Pegar Ip e busca o codigo do usuario da sessao
    public void PegarIp() {
        try {
            ipDaMaquina = InetAddress.getLocalHost().getHostAddress();
            //JOptionPane.showMessageDialog(this, ipDaMaquina);
        } catch (UnknownHostException ex) {
            JOptionPane.showMessageDialog(this, "Falha ao setar IP da máquina!!");
        }
        LoginSessao_Dao dao = new LoginSessao_Dao();
        dao.BuscarSessao(ipDaMaquina).forEach((c) -> {
            Cod_usuario = c.getCod_usuario();

        });
    }
    
    public void MostrarData() {
        Date d = new Date();
        SimpleDateFormat f = new SimpleDateFormat("dd/MM/yyyy");
        Data.setText(f.format(d));
        data = Data.getText();
        
    }
    
    public void MostrarHOra() {
        Timer timer = new Timer(1000, new hora());
        timer.start();
        
    }
    
    public void VerificarPermissaoAtenderPaciente(int Cod_usuario2) {
        Cod_usuario2 = Cod_usuario;
        Usuario_Dao udao = new Usuario_Dao();
        udao.ChecarPeril(Cod_usuario2).forEach((u) -> {
            Cod_Perfil_Permitido = u.getCod_Perfil();
        });
        if(Cod_Perfil_Permitido==Cod_usuario){
            JOptionPane.showMessageDialog(null, "Usuário com permissão de acesso!!");
        }else{
            JOptionPane.showMessageDialog(null, "Usuário sem permissão de acesso!!");
        this.dispose();
        }
    }

    /*public void TestarConexao() {
        conexao = null;
        TestarConexao_Dao dao = new TestarConexao_Dao();
        dao.BuscarConexao().forEach((b) -> {
               conexao=  b.getConectado();
        });
        if(conexao.equals("Conectado")){
           Bolinha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Bola Verde.png"))); 
        }else if (conexao.equals(null)){
        Bolinha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Bola Vermelha.png")));
        }
        //00:00:00
        String dia = Hora.getText().substring(6, 8);
        JOptionPane.showMessageDialog(null, dia);
    }*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelPrincipal = new javax.swing.JPanel();
        PainelLogos = new javax.swing.JPanel();
        LogoSistem = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        CadastrosGerais = new javax.swing.JPanel();
        Laboratoriais = new javax.swing.JLabel();
        TC = new javax.swing.JLabel();
        Usuario = new javax.swing.JLabel();
        Colaboradores = new javax.swing.JLabel();
        Sintomas = new javax.swing.JLabel();
        Atalhos = new javax.swing.JPanel();
        Intranet = new javax.swing.JLabel();
        Wareline = new javax.swing.JLabel();
        Atendimentos = new javax.swing.JPanel();
        Atender = new javax.swing.JLabel();
        Pacientes = new javax.swing.JLabel();
        relógio = new javax.swing.JLabel();
        Calendario = new javax.swing.JLabel();
        Data = new javax.swing.JLabel();
        Hora = new javax.swing.JLabel();
        Créditos = new javax.swing.JLabel();
        Avisos = new javax.swing.JPanel();
        TextosAvisos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema monitoramento COVID-19 Versão 0.0.1");

        PainelPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        PainelLogos.setBackground(new java.awt.Color(0, 255, 255));

        LogoSistem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/lOGO SISTEM_1.png"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logo hr_1.png"))); // NOI18N

        javax.swing.GroupLayout PainelLogosLayout = new javax.swing.GroupLayout(PainelLogos);
        PainelLogos.setLayout(PainelLogosLayout);
        PainelLogosLayout.setHorizontalGroup(
            PainelLogosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelLogosLayout.createSequentialGroup()
                .addComponent(LogoSistem, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 480, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PainelLogosLayout.setVerticalGroup(
            PainelLogosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LogoSistem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        CadastrosGerais.setBackground(new java.awt.Color(255, 255, 255));
        CadastrosGerais.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro Gerais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 2, 10))); // NOI18N

        Laboratoriais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Laboratorio2.png"))); // NOI18N
        Laboratoriais.setToolTipText("Gerenciar Alterações Laboratoriais");
        Laboratoriais.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Laboratoriais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LaboratoriaisMouseClicked(evt);
            }
        });

        TC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/tC2.png"))); // NOI18N
        TC.setToolTipText("Gerenciar Alterações TC");
        TC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TCMouseClicked(evt);
            }
        });

        Usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/User2_1.png"))); // NOI18N
        Usuario.setToolTipText("Gerenciar Usuários");
        Usuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UsuarioMouseClicked(evt);
            }
        });

        Colaboradores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Colaboradores.png"))); // NOI18N
        Colaboradores.setToolTipText("Gerenciar Colaboradores");
        Colaboradores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Colaboradores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ColaboradoresMouseClicked(evt);
            }
        });

        Sintomas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Sintomas.png"))); // NOI18N
        Sintomas.setToolTipText("Gerenciar Sintomas");
        Sintomas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sintomas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SintomasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout CadastrosGeraisLayout = new javax.swing.GroupLayout(CadastrosGerais);
        CadastrosGerais.setLayout(CadastrosGeraisLayout);
        CadastrosGeraisLayout.setHorizontalGroup(
            CadastrosGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastrosGeraisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Laboratoriais, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TC, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Sintomas, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Colaboradores, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CadastrosGeraisLayout.setVerticalGroup(
            CadastrosGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastrosGeraisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CadastrosGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Colaboradores, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TC, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Laboratoriais, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sintomas, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Atalhos.setBackground(new java.awt.Color(255, 255, 255));
        Atalhos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Atalhos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 2, 10))); // NOI18N

        Intranet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/lOGO HR INR_2.png"))); // NOI18N
        Intranet.setToolTipText("Acessar a IntraNet do HR");
        Intranet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Intranet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IntranetMouseClicked(evt);
            }
        });

        Wareline.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/lOGO WARE_1.png"))); // NOI18N
        Wareline.setToolTipText("Abrir o Sistema Wareline");
        Wareline.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Wareline.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                WarelineMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout AtalhosLayout = new javax.swing.GroupLayout(Atalhos);
        Atalhos.setLayout(AtalhosLayout);
        AtalhosLayout.setHorizontalGroup(
            AtalhosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AtalhosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Intranet, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Wareline)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        AtalhosLayout.setVerticalGroup(
            AtalhosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AtalhosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AtalhosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Wareline, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Intranet, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Atendimentos.setBackground(new java.awt.Color(255, 255, 255));
        Atendimentos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Atendimentos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 2, 10))); // NOI18N

        Atender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Atender.png"))); // NOI18N
        Atender.setToolTipText("Atender um novo Paciente");
        Atender.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Atender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AtenderMouseClicked(evt);
            }
        });

        Pacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Pacientes.png"))); // NOI18N
        Pacientes.setToolTipText("Acompanhar os pacientes atendidos");
        Pacientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout AtendimentosLayout = new javax.swing.GroupLayout(Atendimentos);
        Atendimentos.setLayout(AtendimentosLayout);
        AtendimentosLayout.setHorizontalGroup(
            AtendimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AtendimentosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Atender, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Pacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AtendimentosLayout.setVerticalGroup(
            AtendimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AtendimentosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(AtendimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Pacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Atender, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        Atender.getAccessibleContext().setAccessibleDescription("");

        relógio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Relogio.png"))); // NOI18N

        Calendario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Calendario.png"))); // NOI18N

        Data.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        Data.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        Hora.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        Hora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        Créditos.setFont(new java.awt.Font("Arial", 2, 10)); // NOI18N
        Créditos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Créditos.setText("Software desenvolvido por Guilherme Marins dos Santos");

        Avisos.setBackground(new java.awt.Color(255, 255, 255));
        Avisos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Avisos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 2, 10))); // NOI18N

        javax.swing.GroupLayout AvisosLayout = new javax.swing.GroupLayout(Avisos);
        Avisos.setLayout(AvisosLayout);
        AvisosLayout.setHorizontalGroup(
            AvisosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AvisosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TextosAvisos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        AvisosLayout.setVerticalGroup(
            AvisosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AvisosLayout.createSequentialGroup()
                .addComponent(TextosAvisos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout PainelPrincipalLayout = new javax.swing.GroupLayout(PainelPrincipal);
        PainelPrincipal.setLayout(PainelPrincipalLayout);
        PainelPrincipalLayout.setHorizontalGroup(
            PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelLogos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelPrincipalLayout.createSequentialGroup()
                .addGroup(PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelPrincipalLayout.createSequentialGroup()
                        .addGroup(PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Atendimentos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CadastrosGerais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Atalhos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Avisos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Créditos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(relógio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Hora, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Calendario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Data, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        PainelPrincipalLayout.setVerticalGroup(
            PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPrincipalLayout.createSequentialGroup()
                .addComponent(PainelLogos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CadastrosGerais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Atalhos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelPrincipalLayout.createSequentialGroup()
                        .addComponent(Atendimentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 131, Short.MAX_VALUE))
                    .addComponent(Avisos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Data, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Calendario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Hora, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(relógio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelPrincipalLayout.createSequentialGroup()
                        .addComponent(Créditos)
                        .addGap(7, 7, 7)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void IntranetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IntranetMouseClicked
        try {
            URI link = new URI("http://hr.org/intra/");
            try {
                Desktop.getDesktop().browse(link);
            } catch (IOException ex) {
                Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (URISyntaxException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_IntranetMouseClicked

    private void WarelineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WarelineMouseClicked
        try {
            Runtime.getRuntime().exec("cmd.exe /c start c:warewin/menu.exe");
        } catch (IOException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_WarelineMouseClicked

    private void LaboratoriaisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LaboratoriaisMouseClicked
        TelaGerenciarAlteracoesLaboratoriais m = new TelaGerenciarAlteracoesLaboratoriais();
        m.setVisible(true);
    }//GEN-LAST:event_LaboratoriaisMouseClicked

    private void UsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsuarioMouseClicked
        TelaGerenciarUsuario m = new TelaGerenciarUsuario();
        m.setVisible(true);
    }//GEN-LAST:event_UsuarioMouseClicked

    private void SintomasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SintomasMouseClicked
        TelaGerenciarSintomas m = new TelaGerenciarSintomas();
        m.setVisible(true);
    }//GEN-LAST:event_SintomasMouseClicked

    private void ColaboradoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ColaboradoresMouseClicked
        TelaGerenciarColaboradores m = new TelaGerenciarColaboradores();
        m.setVisible(true);
    }//GEN-LAST:event_ColaboradoresMouseClicked

    private void TCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TCMouseClicked
        TelaGerenciarAlteracoesTC m = new TelaGerenciarAlteracoesTC();
        m.setVisible(true);
    }//GEN-LAST:event_TCMouseClicked

    private void AtenderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AtenderMouseClicked
        
        //Metodo para fitrar o usuario se caso ele tiver permissão de acesso
        int Cod_usuario2 = Cod_usuario;
        Usuario_Dao udao = new Usuario_Dao();
        udao.ChecarPeril(Cod_usuario2).forEach((u) -> {
            Cod_Perfil_Permitido = u.getCod_Perfil();
        });
        if(Cod_Perfil_Permitido==1){ // 1 é o código do perfil médico
            TelaAtenderPaciente m = new TelaAtenderPaciente();
            m.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "Usuário sem permissão de acesso!!");
        }
    
    }//GEN-LAST:event_AtenderMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Atalhos;
    private javax.swing.JLabel Atender;
    private javax.swing.JPanel Atendimentos;
    private javax.swing.JPanel Avisos;
    private javax.swing.JPanel CadastrosGerais;
    private javax.swing.JLabel Calendario;
    private javax.swing.JLabel Colaboradores;
    private javax.swing.JLabel Créditos;
    private javax.swing.JLabel Data;
    private javax.swing.JLabel Hora;
    private javax.swing.JLabel Intranet;
    private javax.swing.JLabel Laboratoriais;
    private javax.swing.JLabel LogoSistem;
    private javax.swing.JLabel Pacientes;
    private javax.swing.JPanel PainelLogos;
    private javax.swing.JPanel PainelPrincipal;
    private javax.swing.JLabel Sintomas;
    private javax.swing.JLabel TC;
    private javax.swing.JLabel TextosAvisos;
    private javax.swing.JLabel Usuario;
    private javax.swing.JLabel Wareline;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel relógio;
    // End of variables declaration//GEN-END:variables
class hora implements ActionListener {
        
        @Override
        public void actionPerformed(ActionEvent ae) {
            Calendar now = Calendar.getInstance(TimeZone.getTimeZone("GMT-03:00"));
            Hora.setText(String.format("%1$tH:%1$tM:%1$tS", now));
        }
    }
}
